services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s

  gateway:
    image: tensormesh/lmignite-gateway:latest
    ports:
      - 8000:8000
    volumes:
      - gateway_data:/root
    networks:
      - demo-network
    healthcheck:
      test: ["CMD-SHELL", "nc -zv localhost 8000"]
      interval: 10s
      timeout: 5s

  migrate:
    image: tensormesh/lmignite-ui:latest
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=demo
    command: pnpm migrate:latest
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - demo-network
    restart: "no"

  app:
    image: tensormesh/lmignite-ui:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=demo
      - GATEWAY_API_URL=http://gateway:8000
      - ANONYMOUS_MODE=true
      # in anonymous mode, these following vars are ignored
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - GOOGLE_CALLBACK_URL=http://localhost:3001/auth/google/callback
      - GITHUB_CLIENT_ID=your-github-client-id
      - GITHUB_CLIENT_SECRET=your-github-client-secret
      - GITHUB_CALLBACK_URL=http://localhost:3001/auth/github/callback

    depends_on:
      postgres:
        condition: service_healthy
      gateway:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - demo-network
    restart: unless-stopped
    command: pnpm start:prod

volumes:
  postgres_data:
    driver: local
  gateway_data:
    driver: local

networks:
  demo-network:
    driver: bridge
